"""Add featured_image_url and seo_keywords to BlogPost

Revision ID: 729de26c5c0c
Revises: 2b8cc40f8da7
Create Date: 2026-01-24 10:05:08.543551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729de26c5c0c'
down_revision = '2b8cc40f8da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('seo_keywords', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('seo_keywords')
        batch_op.drop_column('featured_image_url')

    # ### end Alembic commands ###
