"""add name to doctor profile

Revision ID: a4653b5df8f7
Revises: 6479be7c3389
Create Date: 2026-01-26 09:17:36.708944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4653b5df8f7'
down_revision = '6479be7c3389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_profile', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
